### ISSUE TITLE
Password can not be found

### ISSUE THREAD

**Issue by s00500** [dvcrn/go-rekordbox#1]
Hey there, awesome library!

I do have some troubel thought making it connect to the db, can you add some comments on how you intend to retrieve the password ?

I could make it work using the static password I found here:

https://github.com/mganss/CueGen/blob/19878e6eb3f586dee0eb3eb4f2ce3ef18309de9d/CueGen/Generator.cs#L5

Any info is welcome, Thanks

(Other side note: could not make it compile on my M1 mac first, as the crypto lib fights with homebrews install directories... fixed it by setting 2 env vars to point the c compiler to the right dependencies
```
export CGO_LDFLAGS="-L/opt/homebrew/opt/openssl@3/lib"
export CGO_CPPFLAGS="-I/opt/homebrew/opt/openssl@3/include"
```
)

**Comment by dvcrn** [comment]
Hmm you're right, it looks like Rekordbox changed the location of where the password can be found in between versions, so this needs adjusting to make it find the new one automatically 

Would be nice to know how the project you linked extracted the password, I'll try to take a look but in the meantime if you have some time at hand, please feel free to add a PR that changes the cipher key to the updated one, and maybe a reference to the version it was tested on

**Comment by s00500** [comment]
Sounds like a good idea, will do so.

Another random question that just came up: for inserting new content I can easily create a uuid, but what about the normal IDs ? any tips on creating them ?

**Comment by s00500** [comment]
basically solved by #2 shall we close this ?

**Comment by dvcrn** [comment]
Regarding your question, I did a bit of digging through my local database and dumped songs in order of their ID. Looks like this: 

```
5870648 (820fe80f-7dc4-4f74-be6c-580ebf2c7dc0): 9A - 123 - Drop The Pressure (Purple Disco Machine Remix)
6143424 (7ed3e47f-22e7-410e-94ea-b2c12b02802e): 10B - 150 - Sun Goes Down (Extended Mix)
6443381 (d1eb32f7-614a-4f91-b3ce-97eda5be9c92): 3A - 130 - Black Lion (Extended Mix)
6493982 (687c1378-d26d-4b98-bbf2-5abd0244500b): 7A - 122 - Oh La La (feat. Mougleta) (Extended Mix)
6536264 (369d324c-5a36-47d8-b0ff-9201650ee02e): 10B - 142 - Herz an Herz (Manian Remix)
6580351 (c5a88399-e93c-4cf2-9954-0e4970e16ebf): 3A - 87 - Freddy K
6746591 (eda43401-1e4b-482c-a099-22c11634acad): 8A - 134 - The Game Changer (Original Mix)
6848067 (7b308a28-9d6e-4728-920c-80ecadfa7713): 4A - 150 - Because Of You (Extended Mix)
7074852 (52135c70-004d-4075-ae24-8911f1f0b62e): 10A - 128 - Beautiful Now (Dirty South - Extended Mix)
7231033 (8fc9a4fb-84c7-4ea9-99cf-a78cf995ed49): 11B - 138 - Oblivion (Extended Mix)
7933851 (e417e79b-43c3-4ba3-8d5e-b4b29ba03855): 5A - 130 - Spectrum (A-Trak & Clockwork Remix)
8521238 (bb327597-2d3e-4c82-82b2-9971763da0ef): 12A - 124 - Like I Do feat. Brooke Tomlinson (Zookëper Extended Remix)
8759124 (6b1f14b7-6e25-46a2-b1ed-64884fd4109d): 9B - 135 - Vivaldi (Extended Mix)
8893643 (ad1d8c55-c4ad-460c-bb5c-1efd2eaee3c3): 7A - 101 - Go Loko
9066755 (3ba0d4df-d224-44af-8d64-49b98dcec517): 4A - 127 - Get Get Down (Original Mix)
9317943 (08a4cb4e-4384-41a7-a8c9-a1f9ea3d306e): 3A - 136 - Driving Force (Indepth Rmx)
9414573 (ce40dcf8-d944-4128-908e-da354380a4a7): 11A - 127 - Don't Stop The Party (Intro)
9732725 (1c2eb8d1-248c-4851-a7b3-467917152a0a): 10B - 128 - Shivers (Jax Jones Extended Remix)
10029277 (1ed1ceaf-595b-4e1a-a223-3ddba2b5a655): 2A - 124 - Dare Me (Extended Mix)
```

Doesn't look to be purely sequential. I would assume we can just randomly generate the UUID, and pick an ID that's higher than the previous max. Hopefully, rekordbox has mechanisms in place to avoid ID conflicts when importing songs...

**Comment by s00500** [comment]
@dvcrn Haha ok I will do that...

**Comment by s00500** [comment]
addition: seems to work fine, thanks for updating the definitions  :-)
